# This is a basic workflow to help you get started with Actions

name: Runtime Workflow
on:
  schedule: # Run workflow automatically
    # This will make it run every hour
    - cron: "15 14 1 * *"
    # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
  workflow_dispatch:
jobs:
  get-office-quotes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Let the magic happen
        uses: actions/setup-node@v1
        with:
          node-version: 14.6.0

      - name: Install dependencies
        run: yarn

      - name: Run Node.js script
        run: node .

      - name: Disable rebase during pull
        run: git pull --no-rebase

      - name: Check for changes
        id: check_changes
        run: |
          changes=$(git diff)
          if [ -n "$changes" ]; then
            echo "::set-output name=changes::true"
          else
            echo "::set-output name=changes::false"
          fi

      - name: Add changes to git
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git add .
          git config --global user.name "musab"
          git config --global user.email "musab.rasheed@yahoo.com"
          git commit -m "[Automated] README updated with new Office quote."

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  update-readme-with-blog:
    needs: get-office-quotes
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
